#!/bin/bash
    
# announce.sh - Announce the Codespace setup and instructions
(cd /workspaces/codespaces-blank/cis190_codespace && git pull -q || exit 1)
python3 -m rich.markdown -w 80 cis190_codespace/README.md
echo "Remember to run 'source' $SHELL_RC to apply changes."
echo "To start the lab manager, run 'start' in your terminal."
